import { Item } from "../AddAppointmentFields.ts/AddAppointmentInputs.type";

export const addAppointmentFieldsConfig: Item[] = [
  {
    category: "layout",
    type: "box",
    gap: 0.5,
    children: [
      {
        category: "field",
        fieldType: "text",
        id: "patient_name",
        testId: "patient_name",
        name: "patient_name",
        label: "Patient",
        placeholder: "Please choose or add new patient",
      },
      {
        category: "field",
        fieldType: "switch",
        id: "switch_input_method",
        testId: "switch_input_method",
        name: "switch_input_method",
        checkedChildren: "default",
        unCheckedChildren: "QR",
        defaultChecked: false,
      },
    ],
  },
  {
    category: "layout",
    type: "hStack",
    gap: 0.5,
    children: [
      {
        category: "field",
        fieldType: "select",
        id: "doctor",
        testId: "doctor",
        name: "doctor",
        label: "Doctor",
        placeholder: "Select a doctor",
        options: [
          { value: "ahmed", label: "ahmed" },
          { value: "taha", label: "taha" },
        ],
      },
      {
        category: "field",
        fieldType: "select",
        id: "room",
        testId: "room",
        name: "room",
        label: "Room",
        defaultValue: "room_1",
        options: [
          { value: "room_1", label: "Room 1" },
          { value: "room_2", label: "Room 2" },
          { value: "room_3", label: "Room 3" },
          { value: "room_4", label: "Room 4" },
        ],
      },
      {
        category: "field",
        fieldType: "select",
        id: "status",
        testId: "status",
        name: "status",
        label: "Status",
        defaultValue: "open",
        options: [
          { value: "open", label: "Open" },
          { value: "confirmed", label: "Confirmed" },
          { value: "check_in", label: "Check In" },
          { value: "in_progress", label: "In Progress" },
          { value: "completed", label: "Completed" },
          { value: "delayed", label: "Delayed" },
          { value: "canceled", label: "Canceled" },
          { value: "no_show", label: "No Show" },
        ],
      },
    ],
  },
  {
    category: "layout",
    type: "hStack",
    gap: 0.5,
    children: [
      {
        category: "field",
        fieldType: "datePicker",
        id: "day",
        testId: "day",
        name: "day",
        label: "Day",
        defaultValue: `${new Date()}`,
        format: "YYYY-MM-DD",
      },
      {
        category: "field",
        fieldType: "timePicker",
        id: "start_time",
        testId: "start_time",
        name: "start_time",
        label: "Start",
        use12Hours: true,
        defaultValue: `${new Date()}`,
        format: "HH:MM A",
      },
      {
        category: "field",
        fieldType: "timePicker",
        id: "end_time",
        testId: "end_time",
        name: "end_time",
        label: "End",
        defaultValue: `${new Date()}`,
        use12Hours: true,
        format: "HH:MM A",
      },
    ],
  },
  {
    category: "layout",
    type: "hStack",
    gap: 0.5,
    children: [
      {
        category: "field",
        fieldType: "select",
        id: "type",
        testId: "type",
        name: "type",
        label: "Type",
        placeholder: "Select a doctor",
        options: [
          { value: "ahmed", label: "ahmed" },
          { value: "taha", label: "taha" },
        ],
      },
      {
        category: "field",
        fieldType: "select",
        id: "room",
        testId: "room",
        name: "room",
        label: "Room",
        defaultValue: "room_1",
        options: [
          { value: "room_1", label: "Room 1" },
          { value: "room_2", label: "Room 2" },
          { value: "room_3", label: "Room 3" },
          { value: "room_4", label: "Room 4" },
        ],
      },
      {
        category: "field",
        fieldType: "select",
        id: "status",
        testId: "status",
        name: "status",
        label: "Status",
        defaultValue: "open",
        options: [
          { value: "open", label: "Open" },
          { value: "confirmed", label: "Confirmed" },
          { value: "check_in", label: "Check In" },
          { value: "in_progress", label: "In Progress" },
          { value: "completed", label: "Completed" },
          { value: "delayed", label: "Delayed" },
          { value: "canceled", label: "Canceled" },
          { value: "no_show", label: "No Show" },
        ],
      },
    ],
  },
];
