import { Item } from "../AddAppointmentFields/AddAppointmentInputs.type";

export const addAppointmentFieldsConfig: Item[] = [
  {
    category: "layout",
    type: "box",
    gap: 0.5,
    children: [
      {
        category: "field",
        fieldType: "text",
        id: "patient_name",
        testId: "patient_name",
        name: "patient_name",
        schemaName: "patient_name",
        label: "apInputs.patient_name.label",
        placeholder: "apInputs.patient_name.placeholder",
        validation: [{ type: "required", required: true }],
      },
      {
        category: "field",
        fieldType: "switch",
        id: "switch_input_method",
        testId: "switch_input_method",
        name: "switch_input_method",
        schemaName: "switch_input_method",
        checkedChildren: "no qr",
        unCheckedChildren: "QR",
        defaultChecked: false,
        validation: [{ type: "required", required: true }],
      },
    ],
  },
  {
    category: "layout",
    type: "hStack",
    gap: 0.5,
    children: [
      {
        category: "field",
        fieldType: "select",
        id: "doctor",
        testId: "doctor",
        name: "doctor",
        schemaName: "doctor",
        label: "apInputs.doctor.label",
        placeholder: "apInputs.doctor.placeholder",
        options: [
          { value: "ahmed", label: "apInputs.doctor.options.ahmed" },
          { value: "taha", label: "apInputs.doctor.options.taha" },
        ],
        validation: [{ type: "required", required: true }],
      },
      {
        category: "field",
        fieldType: "select",
        id: "room",
        testId: "room",
        name: "room",
        schemaName: "room",
        label: "apInputs.room.label",
        defaultValue: "room_1",
        options: [
          { value: "room_1", label: "apInputs.room.options.room_1" },
          { value: "room_2", label: "apInputs.room.options.room_2" },
          { value: "room_3", label: "apInputs.room.options.room_3" },
          { value: "room_4", label: "apInputs.room.options.room_4" },
        ],
        validation: [{ type: "required", required: true }],
      },
      {
        category: "field",
        fieldType: "select",
        id: "status",
        testId: "status",
        name: "status",
        schemaName: "status",
        label: "apInputs.status.label",
        defaultValue: "open",
        options: [
          { value: "open", label: "apInputs.status.options.open" },
          { value: "confirmed", label: "apInputs.status.options.confirmed" },
          { value: "check_in", label: "apInputs.status.options.check_in" },
          {
            value: "in_progress",
            label: "apInputs.status.options.in_progress",
          },
          { value: "completed", label: "apInputs.status.options.completed" },
          { value: "delayed", label: "apInputs.status.options.delayed" },
          { value: "canceled", label: "apInputs.status.options.canceled" },
          { value: "no_show", label: "apInputs.status.options.no_show" },
        ],
        validation: [{ type: "required", required: true }],
      },
    ],
  },
  {
    category: "layout",
    type: "hStack",
    gap: 0.5,
    children: [
      {
        category: "field",
        fieldType: "datePicker",
        id: "day",
        testId: "day",
        name: "day",
        schemaName: "day",
        label: "apInputs.day.label",
        defaultValue: "today",
        format: "DD/MM/YYYY",
        validation: [
          { type: "required", required: true },
          {
            type: "later_than",
            date: "today",
          },
        ],
      },
      {
        category: "field",
        fieldType: "timePicker",
        id: "start_time",
        testId: "start_time",
        name: "start_time",
        schemaName: "start_time",
        label: "apInputs.start_time.label",
        use12Hours: true,
        defaultValue: "now",
        format: "hh:mm a",
        validation: [
          { type: "required", required: true },
          { type: "time_earlier_than", fields: ["end_time"] },
        ],
      },
      {
        category: "field",
        fieldType: "timePicker",
        id: "end_time",
        testId: "end_time",
        name: "end_time",
        schemaName: "end_time",
        label: "apInputs.end_time.label",
        defaultValue: "next",
        use12Hours: true,
        format: "hh:mm a",
        validation: [
          { type: "required", required: true },
          { type: "time_later_than", fields: ["start_time"] },
        ],
      },
    ],
  },
  {
    category: "layout",
    type: "hStack",
    gap: 0.5,
    children: [
      {
        category: "field",
        fieldType: "select",
        id: "type",
        testId: "type",
        name: "type",
        schemaName: "type",
        label: "apInputs.type.label",
        defaultValue: "examination",
        options: [
          { value: "examination", label: "apInputs.type.options.examination" },
          { value: "follow_up", label: "apInputs.type.options.follow_up" },
          {
            value: "consultation",
            label: "apInputs.type.options.consultation",
          },
          {
            value: "routine_treatment",
            label: "apInputs.type.options.routine_treatment",
          },
          {
            value: "extended_treatment",
            label: "apInputs.type.options.extended_treatment",
          },
          { value: "emergency", label: "apInputs.type.options.emergency" },
          { value: "endo", label: "apInputs.type.options.endo" },
        ],
        validation: [{ type: "required", required: true }],
      },
      {
        category: "field",
        fieldType: "select",
        id: "subtype",
        testId: "subtype",
        name: "subtype",
        schemaName: "subtype",
        label: "apInputs.subtype.label",
        defaultValue: "",
        options: [
          { value: "subtype_1", label: "apInputs.subtype.options.subtype_1" },
          { value: "subtype_2", label: "apInputs.subtype.options.subtype_2" },
          { value: "subtype_3", label: "apInputs.subtype.options.subtype_3" },
          { value: "subtype_4", label: "apInputs.subtype.options.subtype_4" },
        ],
        validation: [{ type: "required", required: false }],
      },
      {
        category: "field",
        fieldType: "datePicker",
        id: "created",
        testId: "created",
        name: "created",
        schemaName: "created",
        label: "apInputs.created.label",
        placeholder: "apInputs.created.placeholder",
        format: "DD/MM/YYYY",
        validation: [
          { type: "required", required: false },
          {
            type: "earlier_than",
            date: "today",
          },
        ],
        dateLimit: {
          status: "after",
          date: "today",
        },
      },
    ],
  },
  {
    category: "field",
    fieldType: "select",
    id: "assistants",
    testId: "assistants",
    name: "assistants",
    schemaName: "assistants",
    label: "apInputs.assistants.label",
    defaultValue: "",
    options: [
      {
        value: "assistant_1",
        label: "apInputs.assistants.options.assistant_1",
      },
      {
        value: "assistant_2",
        label: "apInputs.assistants.options.assistant_2",
      },
    ],
    validation: [{ type: "required", required: false }],
  },
  {
    category: "field",
    fieldType: "textarea",
    id: "description",
    testId: "description",
    name: "description",
    schemaName: "description",
    label: "apInputs.description.label",
    placeholder: "apInputs.description.placeholder",
    validation: [{ type: "required", required: false }],
  },
  {
    category: "UI",
    type: "title",
    text: "apInputs.diagnostic_fees_title.text",
    level: 3,
  },
  {
    category: "field",
    fieldType: "radio",
    id: "diagnostic_fees",
    testId: "diagnostic_fees",
    name: "diagnostic_fees",
    schemaName: "diagnostic_fees",
    defaultValue: "none",
    options: [
      { value: "none", label: "apInputs.diagnostic_fees.options.none" },
      {
        value: "collected",
        label: "apInputs.diagnostic_fees.options.collected",
      },
      {
        value: "add_to_next_invoice",
        label: "apInputs.diagnostic_fees.options.add_to_next_invoice",
      },
    ],
    validation: [{ type: "required", required: false }],
  },
  {
    category: "field",
    fieldType: "number",
    id: "collected_diagnostic_fees",
    testId: "collected_diagnostic_fees",
    name: "collected_diagnostic_fees",
    schemaName: "collected_diagnostic_fees",
    defaultValue: 100,
    validation: [{ type: "required", required: false }],
  },
  {
    category: "field",
    fieldType: "select",
    id: "collected_diagnostic_fees_options",
    testId: "collected_diagnostic_fees_options",
    name: "collected_diagnostic_fees_options",
    schemaName: "collected_diagnostic_fees_options",
    defaultValue: "cash",
    options: [
      {
        value: "cash",
        label: "apInputs.collected_diagnostic_fees_options.options.cash",
      },
      {
        value: "card",
        label: "apInputs.collected_diagnostic_fees_options.options.card",
      },
      {
        value: "insurance",
        label: "apInputs.collected_diagnostic_fees_options.options.insurance",
      },
      {
        value: "cheque",
        label: "apInputs.collected_diagnostic_fees_options.options.cheque",
      },
      {
        value: "voucher",
        label: "apInputs.collected_diagnostic_fees_options.options.voucher",
      },
      {
        value: "bank_transfer",
        label:
          "apInputs.collected_diagnostic_fees_options.options.bank_transfer",
      },
      {
        value: "mobile_wallet",
        label:
          "apInputs.collected_diagnostic_fees_options.options.mobile_wallet",
      },
      {
        value: "other",
        label: "apInputs.collected_diagnostic_fees_options.options.other",
      },
    ],
    validation: [{ type: "required", required: false }],
  },
  {
    category: "field",
    fieldType: "select",
    id: "collected_diagnostic_fees_subtype",
    testId: "collected_diagnostic_fees_subtype",
    name: "collected_diagnostic_fees_subtype",
    schemaName: "collected_diagnostic_fees_subtype",
    defaultValue: "",
    options: [
      {
        value: "",
        label: "apInputs.collected_diagnostic_fees_subtype.options.subtype",
      },
      {
        value: "subtype_1",
        label: "apInputs.collected_diagnostic_fees_subtype.options.subtype_1",
      },
      {
        value: "subtype_2",
        label: "apInputs.collected_diagnostic_fees_subtype.options.subtype_2",
      },
    ],
    validation: [{ type: "required", required: false }],
  },
  {
    category: "UI",
    type: "title",
    text: "apInputs.mobile_notification.text",
    level: 3,
  },
  {
    category: "layout",
    type: "hStack",
    gap: 0.5,
    children: [
      {
        category: "field",
        fieldType: "number",
        id: "reminder_before",
        testId: "reminder_before",
        name: "reminder_before",
        schemaName: "reminder_before",
        label: "apInputs.reminder_before.label",
        validation: [{ type: "required", required: false }],
      },
      {
        category: "field",
        fieldType: "select",
        id: "reminder_before_interval",
        testId: "reminder_before_interval",
        name: "reminder_before_interval",
        schemaName: "reminder_before_interval",
        label: "apInputs.reminder_before_interval.label",
        defaultValue: "minutes",
        options: [
          {
            value: "minutes",
            label: "apInputs.reminder_before_interval.options.minutes",
          },
          {
            value: "hours",
            label: "apInputs.reminder_before_interval.options.hours",
          },
          {
            value: "days",
            label: "apInputs.reminder_before_interval.options.days",
          },
          {
            value: "months",
            label: "apInputs.reminder_before_interval.options.months",
          },
        ],
        validation: [{ type: "required", required: false }],
      },
    ],
  },
];
